server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Contenido
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: simple
