server:
  port: 8086

cloudflare:
  r2:
    endpoint: https://beee52aca83c40b49b5c3f40e96b080c.eu.r2.cloudflarestorage.com
    bucket: productsimagenstorage
    access-key: 8363432433e45042b3ec6b897a85280
    secret-key: f3fe9d935d4f89berfewrt4ert43t35afff77d1ba905303b71a0ddce35e21
    region: "auto"
    public-base-url: https://pub-d87eac01978fgh7g93c0ba28e7912.r2.dev
      
      
